import streamlit as st
import numpy as np
import pandas as pd
from PIL import Image
import io
import random
import os
import glob

from core.utils import load_css, convert_to_rgb
from core.processor import (
    apply_flip,
    apply_perspective_warp,
    apply_crop,
    apply_cfa_resampling,
    apply_chromatic_aberration,
    apply_iso_grain,
    artificial_plasticity_v4,
    apply_unsharp_mask,
    chroma_smoothing,
    spectral_grid_injection_v4,
)
from core.analyzer import compute_fft, plot_2d_spectrum, plot_3d_spectrum
from core.metadata import process_metadata, extract_exif

st.set_page_config(
    page_title="The AI Deception Toolkit",
    page_icon="🎭",
    layout="wide",
    initial_sidebar_state="expanded",
)

load_css()


def main():
    load_css()

    with st.sidebar:
        st.title("🎭 Deception Toolkit")

        st.divider()

        mode = st.radio(
            "Toolkit Module",
            ["📊 The Scanner", "📷 Humanizer", "🎭 Faker"],
            index=0,
            label_visibility="collapsed",
        )

        st.divider()

        uploaded_file = st.file_uploader(
            "Image Upload (Max 10MB)", type=["jpg", "jpeg", "png"]
        )

        st.divider()

        st.info("🔒 Privacy: All processing is in RAM. No uploads are stored.")

        st.divider()
        st.markdown("**System Status**: `ONLINE`")
        st.progress(100)

    # --- State Management ---
    if "processed_image" not in st.session_state:
        st.session_state.processed_image = None
    if "processing_type" not in st.session_state:
        st.session_state.processing_type = None

    # --- Global Image Loading ---
    # Check if a sample is selected
    has_sample = (
        "selected_sample" in st.session_state
        and st.session_state.selected_sample is not None
    )

    if uploaded_file is None and not has_sample:
        # Welcome Screen
        st.markdown(
            """
<div style='text-align: center; padding: 40px;'>
<h1>The AI Deception Toolkit</h1>
<p style='color: #9ca3af; font-size: 1.1em; max-width: 800px; margin: 0 auto 30px auto;'>
A companion tool for the blog post: <i>"How to Trick AI Detectors."</i><br>
This interactive demo shows how easily detectors can be tricked by basic image manipulation.
</p>
<div style='display: grid; grid-template-columns: repeat(auto-fit, minmax(250px, 1fr)); gap: 20px; text-align: left;'>
<div style='padding: 20px; background: #1e1e24; border-radius: 12px; border: 1px solid #2d2d3a;'>
<h3 style='color: #00ff41; margin-top: 0;'>📊 The Scanner</h3>
<p style='font-size: 0.9em; color: #a1a1aa; line-height: 1.5;'>
<b>What it does:</b> Visualizes the "invisible" noise.<br>
See the spectral patterns (stars/grids) that detectors use to flag AI images. If you can see it here, the detector can see it too.
</p>
</div>
<div style='padding: 20px; background: #1e1e24; border-radius: 12px; border: 1px solid #2d2d3a;'>
<h3 style='color: #a78bfa; margin-top: 0;'>📷 The Humanizer</h3>
<p style='font-size: 0.9em; color: #a1a1aa; line-height: 1.5;'>
<b>The Goal:</b> Evade Detection.<br>
Takes an AI image and "dirties it up" with simulated lens distortions and grain, washing away the tell-tale mathematical perfection of AI generation.
</p>
</div>
<div style='padding: 20px; background: #1e1e24; border-radius: 12px; border: 1px solid #2d2d3a;'>
<h3 style='color: #f472b6; margin-top: 0;'>🎭 The Faker</h3>
<p style='font-size: 0.9em; color: #a1a1aa; line-height: 1.5;'>
<b>The Goal:</b> Trigger False Positives.<br>
Innoculates a real human photo with synthetic noise patterns, causing it to be falsely flagged as AI-generated by most detectors.
</p>
</div>
</div>
<div style='margin-top: 40px; padding: 20px; background: #121217; border-radius: 8px;'>
<p style='color: #6b7280; font-size: 0.85em; font-family: monospace;'>
&larr; Upload an image in the sidebar yourself or choose from the gallery to start experimenting.
</p>
</div>
</div>
            """,
            unsafe_allow_html=True,
        )

        st.markdown("### 🖼️ Quick Start Gallery")

        ai_samples = sorted(glob.glob("assets/ai/*.*"))
        real_samples = sorted(glob.glob("assets/real/*.*"))

        if not ai_samples and not real_samples:
            st.info(
                "No samples found in assets/ai/ or assets/real/. Please add images."
            )
            return

        # Helper to set sample
        def set_sample(path):
            st.session_state.selected_sample = path

        # Display Columns
        cols = st.columns(4)
        col_idx = 0

        # AI Samples
        for img_path in ai_samples:
            with cols[col_idx % 4]:
                st.image(img_path, caption="AI Generated", width=250)
                st.button(
                    "Load", key=f"btn_{img_path}", on_click=set_sample, args=(img_path,)
                )
            col_idx += 1

        # Real Samples
        for img_path in real_samples:
            with cols[col_idx % 4]:
                st.image(img_path, caption="Real Photo", width=250)
                st.button(
                    "Load", key=f"btn_{img_path}", on_click=set_sample, args=(img_path,)
                )
            col_idx += 1

        return

    # Load Image (Upload or Sample)
    # Load Image (Upload or Sample)
    if uploaded_file:
        # Upload takes precedence, clear sample
        st.session_state.selected_sample = None
        original_array, _ = convert_to_rgb(uploaded_file)
        st.session_state.input_filename = os.path.splitext(uploaded_file.name)[0]
    elif has_sample:
        original_array, _ = convert_to_rgb(st.session_state.selected_sample)
        st.session_state.input_filename = os.path.splitext(
            os.path.basename(st.session_state.selected_sample)
        )[0]
    else:
        return  # Stay on welcome screen

    if original_array is None:
        st.error("Error loading image. Please try another file.")
        return

    # Check size
    if original_array.shape[0] > 1024 or original_array.shape[1] > 1024:
        st.toast(
            "High-Res Image detected. Optimized to 1024px for stability.", icon="⚠️"
        )

    # --- MODE: DASHBOARD ---
    if mode == "📊 The Scanner":
        render_dashboard(original_array, uploaded_file)

    # --- MODE: HUMANIZER ---
    elif mode == "📷 Humanizer":
        render_humanizer(original_array)

    # --- MODE: FAKER ---
    elif mode == "🎭 Faker":
        render_faker(original_array)


def render_dashboard(original_array, uploaded_file):
    st.header("The Scanner: Spectral Analysis")
    mag_spec, _ = compute_fft(original_array)

    # Bento Grid Layout

    # Row 1: Image | 3D Topology
    r1c1, r1c2 = st.columns(2)
    with r1c1:
        st.subheader("Source Image")
        st.image(
            original_array,
            width="stretch",
            caption=f"Resolution: {original_array.shape[1]}x{original_array.shape[0]}",
        )
    with r1c2:
        st.subheader("3D Topology (Noise)")
        st.plotly_chart(plot_3d_spectrum(mag_spec))

    st.divider()

    # Row 2: Frequency Map | EXIF Data
    r2c1, r2c2 = st.columns(2)
    with r2c1:
        st.subheader("Frequency Map")
        st.pyplot(plot_2d_spectrum(mag_spec))
        st.info(
            "💡 **Bright stars** or **grid patterns** in the spectrum usually indicate AI generation."
        )
    with r2c2:
        st.subheader("EXIF Data")
        # Get EXIF data from source
        source = uploaded_file if uploaded_file else st.session_state.selected_sample
        exif_data = extract_exif(source)

        if exif_data:
            # Check if it's a status message
            if "Status" in exif_data and len(exif_data) == 1:
                st.info(exif_data["Status"])
            else:
                # Format for dataframe
                formatted_data = [
                    {"Tag": k, "Value": str(v)} for k, v in exif_data.items()
                ]
                df = pd.DataFrame(formatted_data)

                st.dataframe(
                    df,
                    column_config={
                        "Tag": st.column_config.TextColumn("Tag", width=150),
                        "Value": st.column_config.TextColumn("Value", width="large"),
                    },
                    width=None, # Auto
                    hide_index=True,
                )
        else:
            st.info("No EXIF data found.")


def render_comparison_row(original_array, modified_array):
    """Renders side-by-side spectral analysis."""
    st.divider()
    with st.expander("📉 Spectral Analysis (Comparison)", expanded=True):
        c1, c2 = st.columns(2)

        # Compute FFTs
        mag_orig, _ = compute_fft(original_array)
        mag_mod, _ = compute_fft(modified_array)

        with c1:
            st.markdown("#### 🔹 Original Signal")
            st.pyplot(plot_2d_spectrum(mag_orig))
            st.plotly_chart(
                plot_3d_spectrum(mag_orig),
                key=f"3d_orig_{random.randint(0, 1000)}",
            )

        with c2:
            st.markdown("#### 🔸 Modified Signal")
            st.pyplot(plot_2d_spectrum(mag_mod))
            st.plotly_chart(
                plot_3d_spectrum(mag_mod),
                key=f"3d_mod_{random.randint(0, 1000)}",
            )


def render_humanizer(original_array):
    st.header("The Humanizer")

    col_img, col_tools = st.columns([1.5, 1])

    with col_tools:
        with st.form("humanizer_form"):
            st.subheader("Configuration")

            with st.expander("📐 Composition & Geometry", expanded=True):
                h_crop = st.selectbox(
                    "Crop Aspect Ratio",
                    [
                        "Original",
                        "1:1 (Square)",
                        "4:5 (Portrait)",
                        "16:9 (Landscape)",
                        "9:16 (Story)",
                    ],
                )
                h_perp = st.slider(
                    "Perspective Adjustment",
                    0.0,
                    1.0,
                    0.0,
                    help="Simulate random camera tilt/angle.",
                )
                h_flip = st.checkbox(
                    "Mirror Image (Flip)", help="Simulate selfie mode."
                )

            with st.expander("🎞️ Optical Physics", expanded=True):
                h_optics = st.slider("Lens Distortion", 0.0, 1.0, 0.1)  # User default
                h_cfa = st.checkbox(
                    "Bayer Sensor Softness", value=False
                )  # User default
                h_grain = st.slider(
                    "ISO Grain (Shot Noise)", 0.0, 1.0, 0.1
                )  # User default

            with st.expander("📝 Metadata Injection"):
                h_profile = st.selectbox(
                    "Camera Model", ["None", "iPhone 15 Pro", "Sony A7III"]
                )
                enable_gps = st.checkbox("Inject GPS")
                lat = st.number_input("Latitude", 40.7128)
                lon = st.number_input("Longitude", -74.0060)

            run_btn = st.form_submit_button("Run Simulation", type="primary")

    if run_btn:
        with st.spinner("Simulating optical path..."):
            current = original_array.copy()
            # Pipeline: Flip -> Crop -> Perspective -> CFA -> Optics -> Noise
            current = apply_flip(current, h_flip)
            current = apply_crop(current, h_crop)
            current = apply_perspective_warp(current, h_perp)
            current = apply_cfa_resampling(current, h_cfa)
            current = apply_chromatic_aberration(current, h_optics)
            current = apply_iso_grain(current, h_grain)

            img_pil = Image.fromarray(current)
            buf = io.BytesIO()
            img_pil.save(buf, format="JPEG", quality=95)
            img_bytes = buf.getvalue()

            if h_profile != "None":
                params = {"lat": lat, "lon": lon} if enable_gps else {}
                img_bytes = process_metadata(img_bytes, h_profile, params)

            st.session_state.processed_image = img_bytes
            st.session_state.processing_type = f"humanized"

    with col_img:
        if st.session_state.processed_image and "humanized" in str(
            st.session_state.processing_type
        ):
            st.subheader("Simulation Result")
            res_img = Image.open(io.BytesIO(st.session_state.processed_image))
            res_arr = np.array(res_img)
            st.image(res_img, width="stretch")
            fname = st.session_state.get("input_filename", "image") + "_humanized.jpg"
            st.download_button(
                "⬇️ Download Result",
                st.session_state.processed_image,
                fname,
                "image/jpeg",
            )

        else:
            st.subheader("Original Preview")
            st.image(original_array, width="stretch", caption="Source")

    # Full Width Analysis
    if st.session_state.processed_image and "humanized" in str(
        st.session_state.processing_type
    ):
        # Re-load array for analysis (or check if it persists, safe to reload from bytes)
        res_img_full = Image.open(io.BytesIO(st.session_state.processed_image))
        res_arr_full = np.array(res_img_full)
        render_comparison_row(original_array, res_arr_full)


def render_faker(original_array):
    st.header("The Faker")

    col_img, col_tools = st.columns([1.5, 1])

    with col_tools:
        with st.form("faker_form"):
            st.subheader("Configuration")

            with st.expander("📐 Composition", expanded=True):
                f_crop = st.selectbox(
                    "Crop Aspect Ratio",
                    [
                        "Original",
                        "1:1 (Square)",
                        "4:5 (Portrait)",
                        "16:9 (Landscape)",
                        "9:16 (Story)",
                    ],
                )

            with st.expander("🧬 Generative Artifacts", expanded=True):
                f_grid = st.slider("Stealth Spectral Grid", 0.0, 1.0, 0.6)
                f_plastic = st.slider("Plasticity Smoothing", 0.0, 1.0, 0.5)
                f_crisp = st.slider(
                    "AI Crispness (Unsharp)",
                    0.0,
                    1.0,
                    0.4,
                    help="Simulates hyper-real edge contrast.",
                )
                f_chroma = st.slider("Chrominance Blur", 0.0, 1.0, 0.4)

            with st.expander("🏷️ AI Signing"):
                f_profile = st.selectbox(
                    "Model Signature",
                    ["None", "Google Tag", "ChatGPT Tag", "Midjourney Tag"],
                )
                f_prompt = st.text_area("Prompt", "A futuristic cyberpunk city...")

            run_btn = st.form_submit_button("Run Injection", type="primary")

    if run_btn:
        with st.spinner("Injecting generative artifacts..."):
            current = original_array.copy()
            current = apply_crop(current, f_crop)
            current = artificial_plasticity_v4(current, f_plastic)
            current = apply_unsharp_mask(current, f_crisp)
            current = chroma_smoothing(current, f_chroma)
            current = spectral_grid_injection_v4(current, f_grid)

            img_pil = Image.fromarray(current)
            buf = io.BytesIO()
            img_pil.save(buf, format="PNG")
            img_bytes = buf.getvalue()

            f_params = {"prompt": f_prompt}
            if f_profile != "None":
                img_bytes = process_metadata(img_bytes, f_profile, f_params)

            st.session_state.processed_image = img_bytes
            st.session_state.processing_type = f"faked"

    with col_img:
        if st.session_state.processed_image and "faked" in str(
            st.session_state.processing_type
        ):
            st.subheader("Injection Result")
            res_img = Image.open(io.BytesIO(st.session_state.processed_image))
            res_arr = np.array(res_img)
            st.image(res_img, width="stretch")
            fname = st.session_state.get("input_filename", "image") + "_faked.png"
            st.download_button(
                "⬇️ Download Result",
                st.session_state.processed_image,
                fname,
                "image/png",
            )

        else:
            st.subheader("Original Preview")
            st.image(original_array, width="stretch", caption="Source")

    # Full Width Analysis
    if st.session_state.processed_image and "faked" in str(
        st.session_state.processing_type
    ):
        res_img_full = Image.open(io.BytesIO(st.session_state.processed_image))
        res_arr_full = np.array(res_img_full)
        render_comparison_row(original_array, res_arr_full)


if __name__ == "__main__":
    main()
